### ISSUE TITLE
/msg doesn't work

### ISSUE THREAD

**Issue by ghost** [H1DD3NxN1NJA/ChatManager#10]
Console log: https://pastebin.com/aiH85upp
Default configs

Paper-193 1.15.2
ChatManager 3.6.4

**Comment by H1DD3NxN1NJA** [comment]
Can you please send the full error message, also send me the entire log
when you do /cm debug all, and if anything is missing in any file please
send me that file as well.

**Comment by ghost** [comment]
https://pastebin.com/iJnMx7UL

**Comment by H1DD3NxN1NJA** [comment]
1. [00:41:08] [Server thread/INFO]: [ChatManager] Vault is required to
   use chat manager... disabling plugin.

**Comment by ghost** [comment]
Got a problem here

Vault v1.7.2-b107
https://pastebin.com/ZjDfddBX

**Comment by H1DD3NxN1NJA** [comment]
I'm not to sure, do you have a permissions plugin on your server I.E. PEX or LP?

**Comment by ghost** [comment]
Nope

**Comment by H1DD3NxN1NJA** [comment]
A permissions plugin is required to use chat manager as well

**Comment by ghost** [comment]
Problem has fixed. Thanks.
