### ISSUE TITLE
Adding individual letters blocks command usage.

### ISSUE THREAD

**Issue by Tikkle** [H1DD3NxN1NJA/ChatManager#11]
When you add individual letters (e.g. `e, o, u`) to the `bannedwords.yml` every command on the server is flagged as offensive/foul language even if there is no string after the command (e.g. `/msg` will be blocked even without the full string of `/msg user message`). Meaning you cant execute any command whatsoever. When you change the `Anti_Swear.Commands.Enable: true` to `false` it won't swear check commands or a string after a command (e.g. `/msg user cussword` is not prevented). I assume that's the intended function.

The reason I added individual letters to my `bannedwords.yml` is that users will try to bypass the filter by spacing out the cuss word (e.g. `c u s s w o r d`) and this technique prevents that.

I initially thought upon the use of this plugin that it only detects strings (e.g. "cussword") so I thought that it would only detect if the letter itself was alone (e.g. "t") not if it was paired (e.g. Terry) which is true in terms of the normal chat:  `[RANK] Tikkle: Hello`  isn't blocked but `[RANK] Tikkle: T` is.

When I removed the individual letters everything works just fine. The only downside is, now I have to go into `bannedwords.yml` and space out every single word just to block that bypass.

Is there a way you can fix this so that adding individual letters won't block commands?
If you need further explanation or a more detailed explanation I think I can provide it, but this is probably my best effort at explaining it.

**Comment by H1DD3NxN1NJA** [comment]
Ok I got some good news for you, if you enable increase sensitivity in the
config words that are spaced of will be blocked l i k e that, and
WordsLikeThis

**Comment by Tikkle** [comment]
That seems to work, thanks Ninja!
