### ISSUE TITLE
[Feature Request] Anti_Swear whitelisted words

### ISSUE THREAD

**Issue by Tikkle** [H1DD3NxN1NJA/ChatManager#12]
I've playtested with the `Anti_Swear.Chat.Increase_Sensitivity: true` option and have found a few false positives like blocking valid command arguments or the word "be" and "best" being blocked in sentences, but not alone. I recommend adding a `whitelistedwords.yml` to pull priority from so you can tweak these false positives.

I have also adjusted by `bannedwords.yml` as best I could to hopefully not have these false positives, but alas, some slip through. Having the `whitelistedwords.yml` option in case there is false positives would be a lifesaver. I would be extremely grateful and happy if you could add this :)

**Comment by H1DD3NxN1NJA** [comment]
Hello Tikkle, I saw this and I love the idea! But besides making a new file I just added a section in the bannedwords.yml file called Whitelisted_Words and those words wont be blocked by the antiswear feature for all chat, commands, and sign checks, only IF increase sensitivity is enabled. I just finished coding it and testing it, I'll post an update hopefully today!
