### ISSUE TITLE
The suffix and prefix are not displayed. LuckPerms

### ISSUE THREAD

**Issue by ghost** [H1DD3NxN1NJA/ChatManager#14]
Hello. I am using LuckPerms to manage permissions. I create a group, create a prefix for it and add myself there, but I still have the [Default] prefix. Why is this happening and how do I display my group prefix?

Maybe you need to change something in the config?
Minecraft 1.16.1
spigot-1.16.1
LuckPerms-Bukkit-5.1.93
ChatManager_3.6.6
Vault last
EssentialsX-2.18.0.0

**Comment by H1DD3NxN1NJA** [comment]
Hey, make sure the groups are all set lowercase in chat managers config
chat format. It’s a think with luckperms. If that doesn’t know let me know.

Thanks,
H1DD3NxN1NJA

**Comment by ghost** [comment]
Do I have to register every group I create in the chat manager config file? 
I thought it was enough to create a group in LuckPerms.

**Comment by H1DD3NxN1NJA** [comment]
That’s if you want each group to be configured separately, if you don’t
want to do it just add {vault_prefix} to the Default_Format in replacement
of [default]
