### ISSUE TITLE
Adding someone to a group

### ISSUE THREAD

**Issue by hurtzz** [H1DD3NxN1NJA/ChatManager#18]
Im trying to add someone to a group in chat manager, put I don't now how. im using luckperms. whenever i go to add someone using /lp user {player} parent add, it doesn't show the VIP or member, or owner, or admin in the list. How do i fix this?

**Comment by H1DD3NxN1NJA** [comment]
Players are automatically placed in the group with their permissions plugin
group name. Make sure the group names in chat managers config matches your
permission groups names. Since you’re using luckperms make sure the group
is lowercase and a displayname isn’t set or it won’t work
