### ISSUE TITLE
Chat Group Formatting

### ISSUE THREAD

**Issue by unecesary** [H1DD3NxN1NJA/ChatManager#3]
Im trying to set up different chat format group for staff members, i have the PEX groups set and made, the players are in that group, and the chat format in ChatManager is made, it works for me with the owner group, but doesnt for the helper group.  In PEX the group is "Helper" and in chat manager its the same, same spelling and capital letter. The Helper group has a lower weight than the other groups. So im not sure what the issue is. Any ideas?

ChatManager Config: https://pastebin.com/ajKWimGm
PEX Perms: https://pastebin.com/87fAYEhk

**Comment by H1DD3NxN1NJA** [comment]
I'm very sorry for the late response, I don't come on here to often to check if there are any issues since not many people open an issue here. 
I'm not sure what could be causing this problem, everything looks correct, but here is some things you can do to try and fix it.
1. Make sure vault is updated to the latest version.
2. Make sure chat manager is updated to the latest version.
3. If the players are added to another rank with a higher weight, the chat format may look at the other rank and not the staff rank, preventing them from being placed in the correct chat format.
4. Try removing the weights and see if that does anything.
If none of this works lmk.

**Comment by unecesary** [comment]
They are both updated to the latest versions, and I have tried without
weights and it just used the default format, I tried commenting out the
default so it would force use one of the formats, but it just made the chat
blank. (With and without weights) and the weights are set so the higher
ranks have a heavier weight, so no matter what they are, the staff has the
heavier of the weights within the different groups they may be in

**Comment by H1DD3NxN1NJA** [comment]
Ok, try this, you said the owner group works just fine, so maybe add what you have in your owner format to the helperplus and helper but besides the owner prefix add {vault_prefix} to those ranks. I'm asking you to do this cause there are a lot of placeholders in the group, it should work fine with them, but it could be causing something to not work properly.

**Comment by unecesary** [comment]
I will test out using only the prefix placeholder and get back to you

**Comment by unecesary** [comment]
I cant figure this out, im so confused as to why it doesnt work properly. I was doing more test, took out all the weights, only have chat groups for my current rank, and the staff ranks, gave myself each rank one at a time, only one worked, re added weights, none worked, re arranged the order of the groups in both pex/CM from higher to lower, none worked, gave myself all the ranks to test, one worked. This is so odd and confusing.

**Comment by unecesary** [comment]
Okay, through some more testing and playing around, I think i found what my issue is. I run a prison server, so theres lots of different ranks, and i use PEX groups for the permissions for the groups. so when a player ranks up, it adds and removes groups for every rankup, causing the ones that stay (helper, owner, etc) to be pushed down the line of the permssion groups of the player. Example: https://pastebin.com/tHpKkJ5R

**Comment by unecesary** [comment]
Upon doing some more testing, I tried having no weights on any group, made the Owner group first in my personal PEX groups list, and the owner chat format works. However, when i add a weight to the owner group (only group with one), it no longer works, and reverts back to the default chat format. I need a way to keep the staff ranks first in the PEX group list of players, or have a way ChatManager can see and recognize the weights of PEX groups and format accordingly.

**Comment by FlailoftheLord** [comment]
> Upon doing some more testing, I tried having no weights on any group, made the Owner group first in my personal PEX groups list, and the owner chat format works. However, when i add a weight to the owner group (only group with one), it no longer works, and reverts back to the default chat format. I need a way to keep the staff ranks first in the PEX group list of players, or have a way ChatManager can see and recognize the weights of PEX groups and format accordingly.

whoa, still unsolved?
