### ISSUE TITLE
[Suggestion] For Chat_Format, add per-world configurations

### ISSUE THREAD

**Issue by Jadiction** [H1DD3NxN1NJA/ChatManager#7]
The title pretty much says it all, instead of just changing the format for groups, allow per-world configuration as well.

For example, groups is like:
```
  Groups:
#    Default: #The name of the group, this is case sensitive!
#      Format: "&8[&7Default&8] &7{player} &9> &7{message}" #The format you want the group to have.
#    VIP:
#      Format: "&8[&5VIP&8] &7{displayname} &9> &7{message}"
#    Moderator:
#      Format: "&a[&3Moderator&a] &b{player} &9> &e{message}"
#    Owner:
#      Format: "&b[&6Owner&b] {player} &9> &e{message}"
```
Worlds can be added right below it in the same fashion::
```
  Worlds:
#    Default: #The name of the group, this is case sensitive!
#      Format: "&8[&7Default&8] &7{player} &9> &7{message}" #The format you want the group to have.
#    Spawn:
#      Format: "[Spawn] &7{displayname} &9> &7{message}"
#    Survival:
#      Format: "[Survival] &b{player} &9> &e{message}"
```

**Comment by H1DD3NxN1NJA** [comment]
I'll put this in consideration, but if you want you can use the placeholder {world} to show the world names in the chat format

**Comment by Jadiction** [comment]
@H1DD3NxN1NJA Yeah, I know. I don't use the group formatting, because all I need to do is "(%multiverse_world_alias%) {vault_prefix}&r&7{displayname}&r: {message}" to show their specified world and role. I wanted per-world formatting because I wanted to add specific things like tags, such as factions for only 1 world and not show anything in the others, which currently isn't possible with ChatManager.
