### ISSUE TITLE
[Suggestion] Wild cards

### ISSUE THREAD

**Issue by MikeyRo** [H1DD3NxN1NJA/ChatManager#9]
I did not see anything in the documentation about the possibility of using wild cards.  Is it feasible to have the chat bot configured for wild cards or to be able to check phrases for a specific word?

We have it set to respond to LOL, but it will not if it is "That made me LOL"

Since I am not a coder, I have no idea the difficulty of something like that.  But it would be cool and would cut down considerably on the configuration.

**Comment by H1DD3NxN1NJA** [comment]
That would be a cool idea but I am unsure exactly how to do that atm
